# Generated by Django 6.0.6 on 2026-06-12 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='The rekuest task id', max_length=1000, unique=True)),
                ('parent_id', models.CharField(blank=True, help_text='The parent task id, if any', max_length=1000, null=True)),
                ('assigner_sub', models.CharField(help_text='The raw sub claim of the assigning user', max_length=1000)),
                ('app', models.CharField(help_text='The assigning app', max_length=1000)),
                ('action', models.CharField(help_text='The action hash', max_length=1000)),
                ('args', models.JSONField(blank=True, default=dict, help_text='The arguments the task was assigned with')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigner', models.ForeignKey(blank=True, help_text='The user that assigned the task (resolved from the sub claim)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization the task ran in', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='authentikate.organization')),
            ],
        ),
    ]
