# Generated by Django 6.0.6 on 2026-06-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koherent', '0001_initial'),
        ('testing_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmymodel',
            name='assignation_id',
        ),
        migrations.AddField(
            model_name='historicalmymodel',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
    ]
